icons = "none"

[theme]
name = "modern"
[theme.overrides]
idle_bg = "$*color0"
idle_fg = "$*color3"
info_bg = "$*color0"
info_fg = "$*color3"

good_bg = "$*color0"
good_fg = "$*color2"

warning_bg = "$*color0"
warning_fg = "$*color1"

critical_bg = "$*color0"
critical_fg = "$*color6"

separator = " "


[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mum} MB"
format_swap = "{SUp}%"
warning_mem = 50.0
critical_mem = 90.0

[[block]]
block = "cpu"
interval = 3

[[block]]
block = "battery"
interval = 30
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
