icons = "awesome"

[theme]
name = "modern"
[theme.overrides]
idle_bg = "#252517"
idle_fg = "#30a6e8"
info_bg = "#252517"
info_fg = "#30a6e8"

good_bg = "#252517"
good_fg = "#5becb0"

warning_bg = "#252517"
warning_fg = "#eae448"

critical_bg = "#252517"
critical_fg = "#e62692"

separator = " "


[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mum} MB"
format_swap = "{SUp}%"
warning_mem = 60.0
critical_mem = 90.0

[[block]]
block = "cpu"
interval = 3

[[block]]
block = "load"
interval = 5
format = "{1m}"

[[block]]
block = "battery"
interval = 30
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
